sudo: required
dist: xenial

os: linux

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - axel
    - cpanminus
    - libtest-base-perl
    - libtext-diff-perl
    - libtest-longstring-perl
    - liblist-moreutils-perl
    - libparallel-forkmanager-perl
    - libgd-dev
    - libmpc-dev
    - build-essential
    - libgtk2.0-dev
    - valgrind

env:
  global:
  - JOBS=3
  - LUAJIT_PREFIX=/opt/luajit21
  - LUAJIT_SYSM_PREFIX=/opt/luajit21-sysm
  - LUAJIT_COMMON_XCFLAGS="-DLUA_USE_APICHECK -DLUA_USE_ASSERT -DLUAJIT_NUMMODE=2 -msse4.2 -O1"
  matrix:
  - LUAJIT_XCFLAGS="$LUAJIT_COMMON_XCFLAGS"
  - LUAJIT_XCFLAGS="-DLUAJIT_ENABLE_LUA52COMPAT $LUAJIT_COMMON_XCFLAGS" LUA52=1
  - LUAJIT_XCFLAGS="-DLUAJIT_USE_VALGRIND -DLUAJIT_USE_SYSMALLOC -DLUAJIT_ENABLE_LUA52COMPAT $LUAJIT_COMMON_XCFLAGS" LUA52=1 FLAGS=-v
  - LUAJIT_XCFLAGS="-DLUAJIT_DISABLE_GC64 -DLUAJIT_ENABLE_LUA52COMPAT $LUAJIT_COMMON_XCFLAGS" LUA52=1

install:
  - git clone https://github.com/openresty/luajit2-test-suite.git ../luajit2-test-suite

script:
  - valgrind --version
  - cd ../luajit2
  - make -j$JOBS CCDEBUG=-g Q= PREFIX=$LUAJIT_PREFIX CC=$CC XCFLAGS="$LUAJIT_XCFLAGS" > build.log 2>&1 || (cat build.log && exit 1)
  - sudo make install PREFIX=$LUAJIT_PREFIX > build.log 2>&1 || (cat build.log && exit 1)
  - cd ../luajit2-test-suite
  - ./run-tests -j $JOBS $FLAGS $LUAJIT_PREFIX
